name: build x64 release

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1
      - name: Build with MSBuild
        run: msbuild /p:Configuration=Release /p:Platform=x64 CS2_External.sln
      - name: Rename EXE to AimStar-dev-${{github.sha}}.exe
        run: |
          del AimStar-dev-*.exe
          ren AimStar.exe AimStar-dev-${{github.sha}}.exe
        working-directory: .\x64\Release\
      - name: Upload the output
        uses: actions/upload-artifact@v2
        with:
          name: ci
          path: .\x64\Release\*
      - name: automatic Release ci
        uses: softprops/action-gh-release@v1
        with:
          name: ci [${{github.sha}}]
          tag_name: ci
          body: |
            **This release has been built by Github Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Full Commit Hash:
            ```
            ${{github.sha}}
            ```
          files: |
            .\x64\Release\AimStar-dev-${{github.sha}}.exe
          prerelease: true
